#!/usr/bin/env bash
set -euo pipefail

# Build tools
sudo apt-get install -y build-essential cmake pkg-config

# Various image format support
sudo apt-get install -y libjpeg8-dev libtiff4-dev libjasper-dev libpng12-dev

# Render images on screen
sudo apt-get install -y libgtk2.0-dev

# Video processing
sudo apt-get install -y libavcodec-dev libavformat-dev libswscale-dev libv4l-dev

# Optimise various OpenCV operations
sudo apt-get install -y libatlas-base-dev gfortran

# Python tools
sudo apt-get install -y python-pip python2.7-d
pip install virtualenv
