#!/usr/bin/env/ bash
set -euo pipefail

VERSION=2.4.10

cd "$(dirname $0)/.."

virtualenv env
. env/bin/activate

pip install numpy

mkdir -p tmp
wget -O tmp/opencv-${VERSION}.zip http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/${VERSION}/opencv-${VERSION}.zip/download
unzip tmp/opencv-${VERSION}.zip

cd tmp/opencv-${VERSION}
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D BUILD_NEW_PYTHON_SUPPORT=ON \
      -D INSTALL_C_EXAMPLES=ON \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D BUILD_EXAMPLES=ON \
      ..
make

sudo make install
sudo ldconfig

# cd ~/.virtualenvs/cv/lib/python2.7/site-packages/
# ln -s /usr/local/lib/python2.7/site-packages/cv2.so cv2.so
# ln -s /usr/local/lib/python2.7/site-packages/cv.py cv.py