#!/usr/bin/env bash
set -euo pipefail

OPENCV_VERSION="2.4.11"

ROOT="$(cd $(dirname $0)/.. && pwd -P)"

VIRTUALENV="${ROOT}/env"

virtualenv $VIRTUALENV

# don't crash on unbound vars in virtualenv activation script
set +u
source "$VIRTUALENV/bin/activate"
set -u

pip install numpy

TMP="${ROOT}/tmp"

mkdir -p "$TMP"
wget -O "${TMP}/opencv-${OPENCV_VERSION}.zip" "http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/${OPENCV_VERSION}/opencv-${OPENCV_VERSION}.zip/download"
unzip -d "$TMP" "${TMP}/opencv-${OPENCV_VERSION}.zip"

BUILD="${TMP}/opencv-${OPENCV_VERSION}/build"

mkdir -p "$BUILD"
cd "$BUILD"
cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D BUILD_NEW_PYTHON_SUPPORT=ON \
      -D INSTALL_C_EXAMPLES=ON \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D BUILD_EXAMPLES=ON \
      ..
make -j4

sudo make install
sudo ldconfig

ln -s /usr/local/lib/python2.7/site-packages/{cv2.so,cv.py} "${VIRTUALENV}/lib/python2.7/site-packages"
