#!/usr/bin/env bash
set -euo pipefail

OPENCV_VERSION="3.0.0"

ROOT="$(cd $(dirname $0)/.. && pwd -P)"

VIRTUALENV="${ROOT}/env"

virtualenv $VIRTUALENV

# don't crash on unbound vars in virtualenv activation script
set +u
source "$VIRTUALENV/bin/activate"
set -u

pip install -r "${ROOT}/requirements.txt"

TMP="${ROOT}/tmp"

mkdir -p "$TMP"
wget -O "${TMP}/opencv-${OPENCV_VERSION}.zip" "https://github.com/Itseez/opencv/archive/${OPENCV_VERSION}.zip"
unzip -d "$TMP" "${TMP}/opencv-${OPENCV_VERSION}.zip"

BUILD="${TMP}/opencv-${OPENCV_VERSION}/build"

mkdir -p "$BUILD"
cd "$BUILD"
cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D BUILD_NEW_PYTHON_SUPPORT=ON \
      -D INSTALL_C_EXAMPLES=ON \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D BUILD_EXAMPLES=ON \
      ..
make -j4

sudo make install
sudo ldconfig

ln -s /usr/local/lib/python2.7/site-packages/cv2.so "${VIRTUALENV}/lib/python2.7/site-packages"
